services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8094:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://quotes.alejoforero.com/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8095:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ALLOWED_ORIGINS=https://quotes.alejoforero.com
